name       : shim-signed
version    : 15.6
release    : 4
source     :
    - https://kojipkgs.fedoraproject.org/packages/shim/15.6/2/x86_64/shim-x64-15.6-2.x86_64.rpm : d6e5d187c979d450d6fe3401dee545617f409b8a31cc90d1e42052f178617be0
license    : BSD-2-Clause
component  : system.base
summary    : Initial UEFI bootloader that handles chaining to a trusted full bootloader under secure boot environments. This package contains the version signed by the UEFI signing service.
description: |
    Initial UEFI bootloader that handles chaining to a trusted full bootloader under secure boot environments. This package contains the version signed by the UEFI signing service.
install    : |
    install -Dm00700 $workdir/boot/efi/EFI/fedora/shim.efi $installdir/%libdir%/shim/shimx64.efi
    install -Dm00700 $workdir/boot/efi/EFI/fedora/mmx64.efi $installdir/%libdir%/shim/mmx64.efi
    install -Dm00700 $workdir/boot/efi/EFI/BOOT/fbx64.efi $installdir/%libdir%/shim/fbx64.efi

    # BOOT.CSV is a UCS-2 LE formatted CSV file. See https://github.com/rhboot/shim/blob/shim-15.5/README.fallback#L48
    install -Dm00700 $pkgfiles/boot.csv $installdir/%libdir%/shim/BOOTX64.CSV
